### ISSUE TITLE
Suggestion: Add transition to portfolio section

### ISSUE THREAD

**Issue by tteltrab** [clsavino/portfolio-cs#2]
The current hover state for the portfolio apps is very abrupt. I'd suggest adding a transition to slow it down a bit (maybe ~200ms). General rule of thumb is that you don't really want flashing on the page when someone moves their cursor over something quickly.

![christi-apps-section](https://cloud.githubusercontent.com/assets/1487463/22227432/3fce2190-e199-11e6-914f-68c9bfb8fbaf.gif)

**Comment by clsavino** [comment]
added 300ms transition
