### ISSUE TITLE
Suggestion: Avoid centering paragraph text

### ISSUE THREAD

**Issue by tteltrab** [clsavino/portfolio-cs#6]
Generally, you want to avoid centering long blocks of text, as it makes them harder for people to read. I'd suggest finding a way to left align here without it throwing off the whole page.

![image](https://cloud.githubusercontent.com/assets/1487463/22227573/fea478bc-e199-11e6-81b8-20c1310f4616.png)

**Comment by clsavino** [comment]
Changed to left justified
