### ISSUE TITLE
Potential Issue: Text in lead section is somewhat hard to read.

### ISSUE THREAD

**Issue by tteltrab** [clsavino/portfolio-cs#7]
Here's what it looks like now:

![image](https://cloud.githubusercontent.com/assets/1487463/22228017/6e294ff8-e19c-11e6-8d54-aef093cce0c1.png)

I'd recommend using some type of transparent background or gradient background to dull out the image behind the text. For example, here's what the head looks like when the element with the background image has a child with a transparent background color:
 
![image](https://cloud.githubusercontent.com/assets/1487463/22228064/b161a5fe-e19c-11e6-8bd4-468dbd8ffc9a.png)

Alternatively, a linear or radial gradient (consecutively):

Linear
```css
    background: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(50,50,50, .4), rgba(0, 0, 0, 0));
```
![image](https://cloud.githubusercontent.com/assets/1487463/22228079/becd6264-e19c-11e6-8269-064cb4e848be.png)

Radial
```css
    radial-gradient(rgba(50,50,50, .6) 30%, rgba(0, 0, 0, 0))
```
![image](https://cloud.githubusercontent.com/assets/1487463/22228107/e43a4634-e19c-11e6-82f8-5dd2c29147dd.png)

**Comment by tteltrab** [comment]
Notice the links in the top right are pretty difficult to see too, you might consider giving them a background of some sort.

**Comment by clsavino** [comment]
Added linear gradient and made links at top bolder
